StockCheckSheet.Web/Controllers/OutputController.cs
using ClosedXML.Excel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Xceed.Document.NET;
using StockCheckSheet.DataAccess.Repository.IRepository;
using StockCheckSheet.Models.ViewModel;
using StockCheckSheet.Utility;
using StockCheckSheetWeb.Models;
using System.Security.Claims;
using Xceed.Words.NET;
using Alignment = Xceed.Document.NET.Alignment;

namespace StockCheckSheetWeb.Controllers
{
    [Authorize(Roles = SD.Role_Admin)]
    public class OutputController : Controller
    {

        private readonly IUnitOfWork _unitOfWork;
        private readonly UserManager<IdentityUser> _userManager;
        public OutputController(IUnitOfWork unitOfWork, UserManager<IdentityUser> userManager)
        {
            _unitOfWork = unitOfWork;
            _userManager = userManager;
        }

        public IActionResult ExportToExcel()
        {
            var outputs = _unitOfWork.Output.GetAll().OrderBy(u => u.Date).ToList();

            using (var workbook = new XLWorkbook())
            {
                var worksheet = workbook.Worksheets.Add("Outputs");

                // Agregar los encabezados
                worksheet.Cell(1, 1).Value = "Date";
                worksheet.Cell(1, 2).Value = "Amount";
                worksheet.Cell(1, 3).Value = "Unit Cost";
                worksheet.Cell(1, 4).Value = "Total Cost";

                // Formato de encabezados
                var headers = worksheet.Range("A1:D1");
                headers.Style.Font.Bold = true;
                headers.Style.Fill.BackgroundColor = XLColor.LightGreen;
                headers.Style.Border.OutsideBorder = XLBorderStyleValues.Thin;
                headers.Style.Alignment.Horizontal = XLAlignmentHorizontalValues.Center;

                // Agregar valores
                int row = 2; // Iniciar en la segunda fila
                foreach (var output in outputs)
                {
                    worksheet.Cell(row, 1).Value = output.Date.ToString("dd/MM/yyyy");
                    worksheet.Cell(row, 2).Value = output.Amount;
                    worksheet.Cell(row, 3).Value = output.UnitCost;
                    worksheet.Cell(row, 4).Value = output.TotalCost;

                    row++;
                }

                // Agregar totales
                worksheet.Cell(row, 1).Value = "Total";
                worksheet.Cell(row, 1).Style.Font.Bold = true;
                worksheet.Cell(row, 2).Value = outputs.Sum(u => u.Amount);
                worksheet.Cell(row, 4).Value = outputs.Sum(u => u.TotalCost);

                // Dar formato a la tabla completamente
                var dataRange = worksheet.Range("A1:D" + row);
                dataRange.Style.Border.OutsideBorder = XLBorderStyleValues.Thin;
                dataRange.Style.Border.InsideBorder = XLBorderStyleValues.Thin;
                dataRange.Style.Font.FontSize = 14;

                // Dar formato a la fecha
                var date = worksheet.Range("A2:A" + row);
                date.Style.Alignment.Horizontal = XLAlignmentHorizontalValues.Center;

                // Dar formato a los valores
                var body = worksheet.Range("B2:D" + row);
                body.Style.Alignment.Horizontal = XLAlignmentHorizontalValues.Right;

                // Formato de pie de página
                var footer = worksheet.Range("B" + row.ToString() + ":D" + row);
                footer.Style.Alignment.Horizontal = XLAlignmentHorizontalValues.Right;

                // Ajustar el ancho de las columnas
                worksheet.Columns().AdjustToContents();

                var stream = new MemoryStream();
                workbook.SaveAs(stream);
                stream.Position = 0;

                string excelName = $"Outputs-{DateTime.Now.ToString("yyyyMMddHHmmssfff")}.xlsx";
                return File(stream, "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", excelName);
            }
        }



        public IActionResult ExportToWord()
        {
            var outputs = _unitOfWork.Output.GetAll().OrderBy(u => u.Date).ToList();

            using (var document = DocX.Create("Outputs.docx"))
            {
                // Agregar un título
                document.InsertParagraph("Outputs")
                    .FontSize(20)
                    .Bold()
                    .Alignment = Alignment.center;

                // Agregar una tabla
                var table = document.AddTable(outputs.Count + 2, 4);
                table.Design = TableDesign.TableGrid;

                // Agregar los encabezados
                table.Rows[0].Cells[0].Paragraphs[0].Append("Date").Bold();
                table.Rows[0].Cells[1].Paragraphs[0].Append("Amount").Bold();
                table.Rows[0].Cells[2].Paragraphs[0].Append("Unit Cost").Bold();
                table.Rows[0].Cells[3].Paragraphs[0].Append("Total Cost").Bold();

                // Agregar valores
                for (int i = 0; i < outputs.Count; i++)
                {
                    table.Rows[i + 1].Cells[0].Paragraphs[0].Append(outputs[i].Date.ToString("dd/MM/yyyy"));
                    table.Rows[i + 1].Cells[1].Paragraphs[0].Append(outputs[i].Amount.ToString());
                    table.Rows[i + 1].Cells[2].Paragraphs[0].Append(outputs[i].UnitCost.ToString());
                    table.Rows[i + 1].Cells[3].Paragraphs[0].Append(outputs[i].TotalCost.ToString());
                }

                // Agregar totales
                table.Rows[outputs.Count + 1].Cells[0].Paragraphs[0].Append("Total").Bold();
                table.Rows[outputs.Count + 1].Cells[1].Paragraphs[0].Append(outputs.Sum(u => u.Amount).ToString());
                table.Rows[outputs.Count + 1].Cells[3].Paragraphs[0].Append(outputs.Sum(u => u.TotalCost).ToString());

                // Insertar la tabla en el documento
                document.InsertTable(table);

                // Guardar el documento en un MemoryStream
                var stream = new MemoryStream();
                document.SaveAs(stream);
                stream.Position = 0;

                string wordName = $"Outputs-{DateTime.Now.ToString("yyyyMMddHHmmssfff")}.docx";
                return File(stream, "application/vnd.openxmlformats-officedocument.wordprocessingml.document", wordName);
            }
        }


        // List all Outputs ---------------------------------------------------
        public IActionResult Index()
        {
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var userId = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier).Value;

            List<Output> objOutputsList = _unitOfWork.Output.GetAll(u => u.ApplicationUserId == userId).ToList();
            return View(objOutputsList);
        }


        // Return view Create ---------------------------------------------------
        public IActionResult Create()
        {
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var userId = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier).Value;

            List<Input> InputList = _unitOfWork.Input.GetAll(u => u.ApplicationUserId == userId.ToString()).ToList();

            OutputVM outputVM = new()
            {
                InputList = InputList,
                Output = new Output(),
            };

            outputVM.Output.Date = DateTime.Now;


            return View(outputVM);
        }
        // Create a new Output ---------------------------------------------------
        [HttpPost]
        public IActionResult Create(OutputVM obj)
        {
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var userId = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier).Value;

            var inputList = _unitOfWork.Input.GetAll(u => u.ApplicationUserId == userId).ToList();
            var outputList = _unitOfWork.Output.GetAll(u => u.ApplicationUserId == userId).ToList();
            var minInputsByDate = inputList.Where(u => u.Date < obj.Output.Date);

            OutputVM outputVM = new()
            {
                InputList = inputList,
                Output = new Output(),
            };

            if (inputList.Count == 0)
            {
                TempData["error"] = "You must have at least one input to create an output!";
                return View(outputVM);
            }

            var totalAmountOutputList = outputList.Sum(u => u.Amount);
            var minDateTimeInput = inputList.Min(u => u.Date);
            var totalAmountInputList = inputList.Sum(u => u.Amount);
            var minAmountInputsByDate = minInputsByDate.Sum(u => u.Amount);

            obj.Output.ApplicationUserId = userId;

            if (obj.Output.Date < minDateTimeInput)
            {
                TempData["error"] = "Date entered is invalid!";
                return View(outputVM);
            }

            if (obj.Output.Amount > totalAmountInputList || (obj.Output.Amount + totalAmountOutputList) > totalAmountInputList)
            {
                TempData["error"] = "Amount overflows total inputs!";
                return View(outputVM);
            }

            if (obj.Output.Amount > minAmountInputsByDate)
            {
                TempData["error"] = "Amount overflows inputs by its date!";
                return View(outputVM);
            }

            if (ModelState.IsValid)
            {
                Stock stock = new Stock();
                stock.Date = obj.Output.Date;
                stock.Amount = obj.Output.Amount;
                stock.UnitCost = obj.Output.UnitCost;
                stock.TotalCost = obj.Output.TotalCost;
                stock.ApplicationUserId = obj.Output.ApplicationUserId;
                _unitOfWork.Stock.Add(stock);

                _unitOfWork.Output.Add(obj.Output);
                _unitOfWork.Save();
                TempData["success"] = "Output created successfully!";

StockCheckSheet.Web/Views/Output/Create.cshtml
@model OutputVM

@{
    ViewData["Title"] = "Create Output";
}


<form method="post" class="d-flex pb-4 justify-content-center">
    <div class="border p-3 mt-4 w-50">
        <div class="row pb-2 d-flex align-items-center">
            <h2 class="col-6 text-primary">Create Output</h2>
            <div class="col-4"></div>
            <div class="col-2">
                <p><strong>Inputs: </strong>@Model.InputList.Sum(u => u.Amount)</p>
            </div>
            
            <hr />
        </div>

        <div class="mb-3 row p-3 py-0">
            <label asp-for="Output.Date" class="p-0 py-2"></label>
            <input asp-for="Output.Date" class="form-control">
            <span asp-validation-for="Output.Date" class="text-danger"></span>
        </div>

        <div class="mb-3 row p-3 py-0">
            <label asp-for="Output.Amount" class="p-0 py-2"></label>
            <input asp-for="Output.Amount" class="form-control" id="amount" />
            <span asp-validation-for="Output.Amount" class="text-danger"></span>
        </div>
        <div class="mb-3 row p-3 py-0">
            <label asp-for="Output.UnitCost" class="p-0 py-2"></label>
            <input asp-for="Output.UnitCost" class="form-control" type="number" id="unitCost" />
            <span asp-validation-for="Output.UnitCost" class="text-danger"></span>
        </div>
        <div class="mb-3 row p-3 py-0">
            <label asp-for="Output.TotalCost" class="p-0 py-2"></label>
            <input asp-for="Output.TotalCost" class="form-control" type="number" id="totalCost" readonly />
            <span asp-validation-for="Output.TotalCost" class="text-danger"></span>
        </div>

        <div class="row py-2">
            <div class="col-6 col-md-4">
                <button type="submit" class="btn btn-primary form-control">Create</button>
            </div>
            <div class="col-6 col-md-4">
                <a asp-controller="Output" asp-action="Index" class="btn btn-secondary border  form-control">
                    Back to List
                </a>
            </div>
        </div>
    </div>
</form>

@section Scripts {
    @{
        <partial name="_ValidationScriptsPartial" />
    }

    <script>
        document.getElementById('amount').addEventListener('input', calculateTotalCost);
        document.getElementById('unitCost').addEventListener('input', calculateTotalCost);

        function calculateTotalCost() {
            var amount = parseFloat(document.getElementById('amount').value) || 0;
            var unitCost = parseFloat(document.getElementById('unitCost').value) || 0;
            var totalCost = amount * unitCost;
            document.getElementById('totalCost').value = totalCost.toFixed(2);
        }

    </script>
}

StockCheckSheet.Web/Views/Output/Delete.cshtml
@model Output

@{
    ViewData["Title"] = "Delete Output";
}


<form method="post" class="d-flex pb-4 justify-content-center">
    <input asp-for="Id" hidden />
    <div class="border p-3 mt-4 ">
        <div class="row pb-2">
            <h2 class="text-primary">Delete Output</h2>
            <hr />
        </div>
        <div class="mb-3 row p-3 py-0">
            <label asp-for="Date" class="p-0 py-2"></label>
            <input asp-for="Date" disabled class="form-control" />
        </div>
        <div class="mb-3 row p-3 py-0">
            <label asp-for="Amount" class="p-0 py-2"></label>
            <input asp-for="Amount" disabled class="form-control" />
        </div>
        <div class="mb-3 row p-3 py-0">
            <label asp-for="UnitCost" class="p-0 py-2"></label>
            <input asp-for="UnitCost" disabled class="form-control" />

        </div>
        <div class="mb-3 row p-3 py-0">
            <label asp-for="TotalCost" class="p-0 py-2"></label>
            <input asp-for="TotalCost" disabled class="form-control" />

        </div>

        <div class="row">
            <div class="col-auto ">
                <button type="submit" class="btn btn-danger form-control">Delete</button>
            </div>
            <div class="col-auto">
                <a asp-controller="Output" asp-action="Index" class="btn btn-secondary border  form-control">
                    Back to List
                </a>
            </div>
        </div>
    </div>
</form>

StockCheckSheet.Web/Views/Output/Edit.cshtml
@model OutputVM

@{
    ViewData["Title"] = "Create Output";
}


<form method="post" class="d-flex pb-4 justify-content-center">
    <input asp-for="Output.Id" hidden />
    <div class="border p-3 mt-4 w-50">
        <div class="row pb-2 d-flex align-items-center">
            <h2 class="col-6 text-primary">Edit Output</h2>
            <div class="col-4"></div>
            <div class="col-2">
                <p><strong>Inputs: </strong>@Model.InputList.Sum(u => u.Amount)</p>
            </div>

            <hr />
        </div>

        <div class="mb-3 row p-3 py-0">
            <label asp-for="Output.Date" class="p-0 py-2"></label>
            <input asp-for="Output.Date" class="form-control">
            <span asp-validation-for="Output.Date" class="text-danger"></span>
        </div>

        <div class="mb-3 row p-3 py-0">
            <label asp-for="Output.Amount" class="p-0 py-2"></label>
            <input asp-for="Output.Amount" class="form-control" id="amount" />
            <span asp-validation-for="Output.Amount" class="text-danger"></span>
        </div>
        <div class="mb-3 row p-3 py-0">
            <label asp-for="Output.UnitCost" class="p-0 py-2"></label>
            <input asp-for="Output.UnitCost" class="form-control" type="number" id="unitCost" />
            <span asp-validation-for="Output.UnitCost" class="text-danger"></span>
        </div>
        <div class="mb-3 row p-3 py-0">
            <label asp-for="Output.TotalCost" class="p-0 py-2"></label>
            <input asp-for="Output.TotalCost" class="form-control" type="number" id="totalCost" readonly />
            <span asp-validation-for="Output.TotalCost" class="text-danger"></span>
        </div>

        <div class="row py-2">
            <div class="col-6 col-md-4">
                <button type="submit" class="btn btn-primary form-control">Update</button>
            </div>
            <div class="col-6 col-md-4">
                <a asp-controller="Output" asp-action="Index" class="btn btn-secondary border  form-control">
                    Back to List
                </a>
            </div>
        </div>
    </div>
</form>

@section Scripts {
    @{
        <partial name="_ValidationScriptsPartial" />
    }

    <script>
        document.getElementById('amount').addEventListener('input', calculateTotalCost);
        document.getElementById('unitCost').addEventListener('input', calculateTotalCost);

        function calculateTotalCost() {
            var amount = parseFloat(document.getElementById('amount').value) || 0;
            var unitCost = parseFloat(document.getElementById('unitCost').value) || 0;
            var totalCost = amount * unitCost;
            document.getElementById('totalCost').value = totalCost.toFixed(2);
        }

    </script>
}

StockCheckSheet.Web/Views/Output/Index.cshtml
@model List<Output>

@{
    ViewData["Title"] = "Outputs";
}


<div class="container pb-4 d-flex flex-column align-items-center">
    <div class="row py-4 d-flex justify-content-between align-items-center">
        <div class="col-auto">
            <h2 class="text-primary mb-0">
                Output List
            </h2>

        </div>
        <div class="col">
            <h2 style="visibility: hidden;">
                -------
            </h2>
        </div>
        <div class="col-auto">
            <a asp-controller="Output" asp-action="Create" class="btn btn-primary mx-2">
                <i class="bi bi-plus-circle"></i> Create New Output
            </a>
            <a asp-controller="Output" asp-action="ExportToExcel" class="btn btn-success mx-2">
                <i class="bi bi-file-earmark-excel"></i> Export to Excel
            </a>
            <a asp-controller="Output" asp-action="ExportToWord" class="btn btn-info mx-2">
                <i class="bi bi-file-earmark-word"></i> Export to Word
            </a>

        </div>
    </div>


    <div class="row">
        <table class="table table-bordered table-striped w-auto">
            <thead>
                <tr>
                    <th>
                        Date
                    </th>
                    <th>
                        Amount
                    </th>
                    <th>
                        Unit Cost
                    </th>
                    <th>
                        Total Cost
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var obj in Model.OrderBy(u => u.Date))
                {
                    <tr>
                        <td>
                            @obj.Date.ToString("dd/MM/yyyy")
                        </td>
                        <td>
                            @obj.Amount
                        </td>
                        <td>
                            $ @obj.UnitCost
                        </td>
                        <td>
                            $ @obj.TotalCost
                        </td>
                        <td>
                            <div class="btn-group" role="group">
                                <a asp-controller="Output" asp-action="Edit" asp-route-id="@obj.Id" class="btn btn-primary mx-2">
                                    <i class="bi bi-pencil-square"></i> Edit
                                </a>
                                <a asp-controller="Output" asp-action="Delete" asp-route-id="@obj.Id" class="btn btn-danger mx-2">
                                    <i class="bi bi-trash-fill"></i> Delete
                                </a>
                            </div>
                        </td>
                    </tr>
                }
                <tr>
                    <th>
                        <strong>Total</strong>
                    </th>
                    <td>
                        @Model.Sum(u => u.Amount)
                    </td>
                    <td>
                    </td>
                    <td>
                        $ @Model.Sum(u => u.TotalCost).ToString("0.00")
                    </td>
                    <td></td>
                </tr>
            </tbody>
        </table>
    </div>
</div>