StockCheckSheet.Web/Controllers/InputController.cs
using AspNetCore.Reporting;
using ClosedXML.Excel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using StockCheckSheet.DataAccess.Repository.IRepository;
using StockCheckSheet.Utility;
using StockCheckSheetWeb.Models;
using System.Data;
using System.Security.Claims;

namespace StockCheckSheetWeb.Controllers
{
    [Authorize(Roles = SD.Role_Admin)]
    public class InputController : Controller
    {

        private readonly IUnitOfWork _unitOfWork;
        private readonly UserManager<IdentityUser> _userManager;
        private readonly IWebHostEnvironment _webHostEnv;

        public InputController(IUnitOfWork unitOfWork, UserManager<IdentityUser> userManager, IWebHostEnvironment webHostEnv)
        {
            _unitOfWork = unitOfWork;
            _userManager = userManager;
            _webHostEnv = webHostEnv;
            System.Text.Encoding.RegisterProvider(System.Text.CodePagesEncodingProvider.Instance);
        }

        public IActionResult ExportToExcel()
        {
            // Obtener los datos
            var inputs = _unitOfWork.Input.GetAll().OrderBy(u => u.Date).ToList();

            using (var workbook = new XLWorkbook())
            {
                var worksheet = workbook.Worksheets.Add("Inputs");

                // Agregar los encabezados
                worksheet.Cell(1, 1).Value = "Date";
                worksheet.Cell(1, 2).Value = "Amount";
                worksheet.Cell(1, 3).Value = "Unit Cost";
                worksheet.Cell(1, 4).Value = "Total Cost";

                // Formato de encabezados
                var headers = worksheet.Range("A1:D1");
                headers.Style.Font.Bold = true;
                headers.Style.Fill.BackgroundColor = XLColor.LightGreen;
                headers.Style.Border.OutsideBorder = XLBorderStyleValues.Thin;
                headers.Style.Alignment.Horizontal = XLAlignmentHorizontalValues.Center;

                // Agregar valores
                int row = 2; // Iniciar en la segunda fila
                foreach (var input in inputs)
                {
                    worksheet.Cell(row, 1).Value = input.Date.ToString("dd/MM/yyyy");
                    worksheet.Cell(row, 2).Value = input.Amount;
                    worksheet.Cell(row, 3).Value = input.UnitCost;
                    worksheet.Cell(row, 4).Value = input.TotalCost;

                    row++;
                }

                // Agregar totales
                worksheet.Cell(row, 1).Value = "Total";
                worksheet.Cell(row, 1).Style.Font.Bold = true;
                worksheet.Cell(row, 2).Value = inputs.Sum(u => u.Amount);
                worksheet.Cell(row, 4).Value = inputs.Sum(u => u.TotalCost);

                // Dar formato a la tabla completamente
                var dataRange = worksheet.Range("A1:D" + row);
                dataRange.Style.Border.OutsideBorder = XLBorderStyleValues.Thin;
                dataRange.Style.Border.InsideBorder = XLBorderStyleValues.Thin;
                dataRange.Style.Font.FontSize = 14;

                // Dar formato a la fecha
                var date = worksheet.Range("A2:A" + row);
                date.Style.Alignment.Horizontal = XLAlignmentHorizontalValues.Center;

                // Dar formato a los valores
                var body = worksheet.Range("B2:D" + row);
                body.Style.Alignment.Horizontal = XLAlignmentHorizontalValues.Right;

                // Formato de pie de página
                var footer = worksheet.Range("B" + row.ToString() + ":D" + row);
                footer.Style.Alignment.Horizontal = XLAlignmentHorizontalValues.Right;

                // Ajustar el ancho de las columnas
                worksheet.Columns().AdjustToContents();

                var stream = new MemoryStream();
                workbook.SaveAs(stream);
                stream.Position = 0;

                string excelName = $"Inputs-{DateTime.Now.ToString("yyyyMMddHHmmssfff")}.xlsx";
                return File(stream, "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", excelName);
            }
        }

        public IActionResult InputsInfo()
        {
            var dt = new DataTable();
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var userId = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier).Value;

            var inputs = _unitOfWork.Input.GetAll(u => u.ApplicationUserId == userId).OrderBy(u => u.Date).ToList();

            // Crear el DataTable
            dt.Columns.Add("Date", typeof(string));
            dt.Columns.Add("Amount", typeof(decimal));
            dt.Columns.Add("UnitCost", typeof(decimal));
            dt.Columns.Add("TotalCost", typeof(decimal));

            // Llenar el DataTable
            foreach (var input in inputs)
            {
                string formattedDate = input.Date.ToString("dd/MM/yyyy");
                dt.Rows.Add(formattedDate, input.Amount, input.UnitCost, input.TotalCost);
            }

            string mimeType = "";
            int extension = 1;
            var path = $"{_webHostEnv.WebRootPath}\\Reports\\rptInputsInfo.rdlc";

            Dictionary<string, string> parameters = new Dictionary<string, string>();
            parameters.Add("prm1", "RDLC Report");
            parameters.Add("prm2", DateTime.Now.ToString("dd-MMM-yyyy"));
            parameters.Add("prm3", "Input Report");

            LocalReport localReport = new LocalReport(path);
            localReport.AddDataSource("dsInputInfo", dt);

            var res = localReport.Execute(RenderType.Pdf, extension, parameters, mimeType);
            return File(res.MainStream, "application/pdf");
        }



        // List all Inputs ---------------------------------------------------
        public IActionResult Index()
        {
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var userId = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier).Value;

            List<Input> objInputsList = _unitOfWork.Input.GetAll(u => u.ApplicationUserId == userId).ToList();
            return View(objInputsList);
        }


        // Return view Create ---------------------------------------------------
        public IActionResult Create()
        {
            var input = new Input();
            input.Date = DateTime.Now;
            return View(input);
        }
        // Create a new Input ---------------------------------------------------
        [HttpPost]
        public IActionResult Create(Input obj)
        {
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var userId = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier).Value.ToString();

            obj.ApplicationUserId = userId;

            if (ModelState.IsValid)
            {
                Stock stock = new Stock();
                stock.Date = obj.Date;
                stock.Amount = obj.Amount;
                stock.UnitCost = obj.UnitCost;
                stock.TotalCost = obj.TotalCost;
                stock.ApplicationUserId = obj.ApplicationUserId;
                _unitOfWork.Stock.Add(stock);

                _unitOfWork.Input.Add(obj);
                _unitOfWork.Save();
                TempData["success"] = "Input created successfully!";
                return RedirectToAction("Index");
            }
            return View();
        }


        // Return view Edit ---------------------------------------------------
        public IActionResult Edit(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            Input inputFromDb = _unitOfWork.Input.Get(u => u.Id == id);

            if (inputFromDb == null)
            {
                return NotFound();
            }
            return View(inputFromDb);
        }
        // Update a Input ---------------------------------------------------
        [HttpPost]
        public IActionResult Edit(Input obj)
        {
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var userId = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier).Value;

            obj.ApplicationUserId = userId;

            if (ModelState.IsValid)
            {
                Stock stock = _unitOfWork.Stock.Get(u => u.ApplicationUserId == userId);

                if(stock != null)
                {
                    stock.Date = obj.Date;
                    stock.Amount = obj.Amount;
                    stock.UnitCost = obj.UnitCost;
                    stock.TotalCost = obj.TotalCost;
                    stock.ApplicationUserId = obj.ApplicationUserId;
                    _unitOfWork.Stock.Update(stock);
                }

                _unitOfWork.Input.Update(obj);
                _unitOfWork.Save();
                TempData["success"] = "Input updated successfully!";
                return RedirectToAction("Index");
            }
            return View();

        }

        // Return view Delete ---------------------------------------------------
        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            Input? inputFromDb = _unitOfWork.Input.Get(u => u.Id == id);

            if (inputFromDb == null)
            {
                return NotFound();
            }
            return View(inputFromDb);
        }
        // Delete a Input ---------------------------------------------------
        [HttpPost, ActionName("Delete")]
        public IActionResult DeletePOST(int? id)
        {
            Input? obj = _unitOfWork.Input.Get(u => u.Id == id);
            if (obj == null)
            {
                return NotFound();
            }

            Stock stock = _unitOfWork.Stock.Get(u => u.Date == obj.Date);

            stock.Date = obj.Date;
            stock.Amount = obj.Amount;

StockCheckSheet.Web/Views/Input/Create.cshtml
@model Input

@{
    ViewData["Title"] = "Create Input";
}


<form method="post" class="d-flex pb-4 justify-content-center">
    <div class="border p-3 mt-4 w-50">
        <div class="row pb-2">
            <h2 class="text-primary">Create Input</h2>
            <hr />
        </div>

        <div class="mb-3 row p-3 py-0">
            <label asp-for="Date" class="p-0 py-2"></label>
            <input asp-for="Date" class="form-control">
            <span asp-validation-for="Date" class="text-danger"></span>
        </div>

        <div class="mb-3 row p-3 py-0">
            <label asp-for="Amount" class="p-0 py-2"></label>
            <input asp-for="Amount" class="form-control" id="amount" />
            <span asp-validation-for="Amount" class="text-danger"></span>
        </div>
        <div class="mb-3 row p-3 py-0">
            <label asp-for="UnitCost" class="p-0 py-2"></label>
            <input asp-for="UnitCost" class="form-control" type="number" id="unitCost" />
            <span asp-validation-for="UnitCost" class="text-danger"></span>
        </div>
        <div class="mb-3 row p-3 py-0">
            <label asp-for="TotalCost" class="p-0 py-2"></label>
            <input asp-for="TotalCost" class="form-control" type="number" id="totalCost" readonly />
            <span asp-validation-for="TotalCost" class="text-danger"></span>
        </div>

        <div class="row py-2">
            <div class="col-6 col-md-4">
                <button type="submit" class="btn btn-primary form-control">Create</button>
            </div>
            <div class="col-6 col-md-4">
                <a asp-controller="Input" asp-action="Index" class="btn btn-secondary border  form-control">
                    Back to List
                </a>
            </div>
        </div>
    </div>
</form>

@section Scripts {
    @{
        <partial name="_ValidationScriptsPartial" />
    }

    <script>
        document.getElementById('amount').addEventListener('input', calculateTotalCost);
        document.getElementById('unitCost').addEventListener('input', calculateTotalCost);

        function calculateTotalCost() {
            var amount = parseFloat(document.getElementById('amount').value) || 0;
            var unitCost = parseFloat(document.getElementById('unitCost').value) || 0;
            var totalCost = amount * unitCost;
            document.getElementById('totalCost').value = totalCost.toFixed(2);
        }

    </script>
}

StockCheckSheet.Web/Views/Input/Delete.cshtml
@model Input

@{
    ViewData["Title"] = "Delete Input";
}


<form method="post" class="d-flex pb-4 justify-content-center">
    <input asp-for="Id" hidden />
    <div class="border p-3 mt-4 ">
        <div class="row pb-2">
            <h2 class="text-primary">Delete Input</h2>
            <hr />
        </div>
        <div class="mb-3 row p-3 py-0">
            <label asp-for="Date" class="p-0 py-2"></label>
            <input asp-for="Date" disabled class="form-control" />
        </div>
        <div class="mb-3 row p-3 py-0">
            <label asp-for="Amount" class="p-0 py-2"></label>
            <input asp-for="Amount" disabled class="form-control" />
        </div>
        <div class="mb-3 row p-3 py-0">
            <label asp-for="UnitCost" class="p-0 py-2"></label>
            <input asp-for="UnitCost" disabled class="form-control" />

        </div>
        <div class="mb-3 row p-3 py-0">
            <label asp-for="TotalCost" class="p-0 py-2"></label>
            <input asp-for="TotalCost" disabled class="form-control" />

        </div>

        <input asp-for="ApplicationUserId" value="@User.Identity.Name" hidden />

        <div class="row">
            <div class="col-auto ">
                <button type="submit" class="btn btn-danger form-control">Delete</button>
            </div>
            <div class="col-auto">
                <a asp-controller="Input" asp-action="Index" class="btn btn-secondary border  form-control">
                    Back to List
                </a>
            </div>
        </div>
    </div>
</form>

StockCheckSheet.Web/Views/Input/Edit.cshtml
@model Input

@{
    ViewData["Title"] = "Edit Input";
}


<form method="post" class="d-flex pb-4 justify-content-center">
    <input asp-for="Id" hidden />
    <div class="border p-3 mt-4 w-50">
        <div class="row pb-2">
            <h2 class="text-primary">Edit Input</h2>
            <hr />
        </div>

        <div class="mb-3 row p-3 py-0">
            <label asp-for="@Model.Date" class="p-0 py-2"></label>
            <input asp-for="@Model.Date" class="form-control">
            <span asp-validation-for="@Model.Date" class="text-danger"></span>
        </div>

        <div class="mb-3 row p-3 py-0">
            <label asp-for="Amount" class="p-0 py-2"></label>
            <input asp-for="Amount" class="form-control" id="amount" />
            <span asp-validation-for="Amount" class="text-danger"></span>
        </div>
        <div class="mb-3 row p-3 py-0">
            <label asp-for="UnitCost" class="p-0 py-2"></label>
            <input asp-for="UnitCost" class="form-control" type="number" id="unitCost" />
            <span asp-validation-for="UnitCost" class="text-danger"></span>
        </div>
        <div class="mb-3 row p-3 py-0">
            <label asp-for="TotalCost" class="p-0 py-2"></label>
            <input asp-for="TotalCost" class="form-control" type="number" id="totalCost" readonly />
            <span asp-validation-for="TotalCost" class="text-danger"></span>
        </div>

        <div class="row py-2">
            <div class="col-6 col-md-4">
                <button type="submit" class="btn btn-primary form-control">Update</button>
            </div>
            <div class="col-6 col-md-4">
                <a asp-controller="Input" asp-action="Index" class="btn btn-secondary border  form-control">
                    Back to List
                </a>
            </div>
        </div>
    </div>
</form>

@section Scripts {
    @{
        <partial name="_ValidationScriptsPartial" />
    }

    <script>
        document.getElementById('amount').addEventListener('input', calculateTotalCost);
        document.getElementById('unitCost').addEventListener('input', calculateTotalCost);

        function calculateTotalCost() {
            var amount = parseFloat(document.getElementById('amount').value) || 0;
            var unitCost = parseFloat(document.getElementById('unitCost').value) || 0;
            var totalCost = amount * unitCost;
            document.getElementById('totalCost').value = totalCost.toFixed(2);
        }

    </script>
}

StockCheckSheet.Web/Views/Input/Index.cshtml
@model List<Input>

@{
    ViewData["Title"] = "Inputs";
}


<div class="container pb-4 d-flex flex-column align-items-center">
    <div class="row py-4 d-flex justify-content-between align-items-center">
        <div class="col-auto">
            <h2 class="text-primary mb-0">
                Input List
            </h2>

        </div>
        <div class="col">
            <h2 style="visibility: hidden;">
                -----------
            </h2>
        </div>
        <div class="col-auto">
            <a asp-controller="Input" asp-action="Create" class="btn btn-primary mx-2">
                <i class="bi bi-plus-circle"></i> Create New Input
            </a>
            <a asp-controller="Input" asp-action="ExportToExcel" class="btn btn-success mx-2">
                <i class="bi bi-file-earmark-excel"></i> Export to Excel
            </a>
        </div>
    </div>


    <div class="row">
        <table class="table table-bordered table-striped w-auto">
            <thead>
                <tr>
                    <th>
                        Date
                    </th>
                    <th>
                        Amount
                    </th>
                    <th>
                        Unit Cost
                    </th>
                    <th>
                        Total Cost
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var obj in Model.OrderBy(u => u.Date))
                {
                    <tr>
                        <td>
                            @obj.Date.ToString("dd/MM/yyyy")
                        </td>
                        <td>
                            @obj.Amount
                        </td>
                        <td>
                            $ @obj.UnitCost
                        </td>
                        <td>
                            $ @obj.TotalCost
                        </td>
                        <td>
                            <div class="btn-group" role="group">
                                <a asp-controller="Input" asp-action="Edit" asp-route-id="@obj.Id" class="btn btn-primary mx-2">
                                    <i class="bi bi-pencil-square"></i> Edit
                                </a>
                                <a asp-controller="Input" asp-action="Delete" asp-route-id="@obj.Id" class="btn btn-danger mx-2">
                                    <i class="bi bi-trash-fill"></i> Delete
                                </a>
                            </div>
                        </td>
                    </tr>
                }
                <tr>
                    <th>
                        <strong>Total</strong>
                    </th>
                    <td>
                        @Model.Sum(u => u.Amount)
                    </td>
                    <td>
                    </td>
                    <td>
                        $ @Model.Sum(u => u.TotalCost).ToString("0.00")
                    </td>
                    <td></td>
                </tr>
            </tbody>
        </table>
    </div>
</div>